#!/bin/sh
#install Broadcom wifi#
sudo apt-get install --reinstall bcmwl-kernel-source
sudo modprobe wl
#update & upgrade#
sudo apt-get update && sudo apt-get upgrade
#install curl#
sudo apt-get install curl
#install aptitude#
sudo apt-get aptitude
#install openssh#
sudo aptitude install openssh-server
#install rvm#
curl -L https://get.rvm.io | bash -s stable --ruby
#install other dependencies#
sudo apt-get install build-essential openssl libreadline6 libreadline6-dev \
curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 \
libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison  \
subversion pkg-config
#install rails#
gem install rails -v 3.2.9
#install chrome#
sudo apt-get install chrome-browser
#install sublime#
sudo add-apt-repository ppa:webupd8team/sublime-text-2
sudo apt-get update
sudo apt-get install sublime-text
#install Cinnamon#
sudo add-apt-repository ppa:gwendal-lebihan-dev/cinnamon-stable
sudo apt-get update
sudo apt-get install cinnamon
#intall vlc#
sudo apt-get install vlc
#install filezilla#
sudo apt-get install filezilla
#install putty#
sudo apt-get install putty
#install git and config#
sudo apt-get install git
git config --global user.name "Quan"
git config --global user.email drixta@gmail.com
#update & upgrade#
sudo apt-get update && sudo apt-get upgrade